version: '3.8'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes: [".:/app'", "/app/node_modules"]
    depends_on:
      - 'postgres'
    ports: ["8080:8080"]
    env_file: .env